name: Deploy Keycloak to Azure App Service

on:
  push:
    branches:
      - main # Executa o workflow ao fazer push na branch "main".

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Login no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build da imagem Docker
    - name: Build Docker image
      run: docker build -t filipaicognitus/keycloak-h2-persistent:latest .

    # 4. Push da imagem para o Docker Hub
    - name: Push Docker image
      run: docker push filipaicognitus/keycloak-h2-persistent:latest

    # 5. Login interativo no Azure
    - name: Log in to Azure
      run: az login

    # 6. Atualizar o App Service no Azure
    - name: Update Azure App Service
      run: |
        az webapp config container set \
          --name meu-keycloak-app \
          --resource-group grupoappkeycloack \
          --docker-custom-image-name filipaicognitus/keycloak-h2-persistent:latest \
          --docker-registry-server-url https://index.docker.io/v1/

